name: Debugging Demo

on:
  workflow_dispatch:
  push:

env:
  USER_1: "foo-user"
  USER_2: "bar-user"

jobs:
  debug_job:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout Repo
      uses: actions/checkout@v4

    # Below we create the USERNAME variable
    # This is done by echo a Key Value pair
    # Below USERNAME is the key and $USER_1 is the value
    # Then we append it to the $GITHUB_ENV file, which is predefined
    # Now the USERNAME variables will be available in subsequent steps
    - name: Step 2 - Set USER_1 as USERNAME
      run: |
        echo "USERNAME=$USER_1" >> $GITHUB_ENV

    - name: Step 3 - Printing USERNAME
      run: |
        echo "Printing USERNAME env variable from previous step"
        echo "USERNAME ========= $USERNAME"
        exit 1

    - name: Step 4 - Printint USER_2
      run: |
        echo $USER_2